services:
  app:
    build: ./frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - 3000

    ports:
      - 127.0.0.1:3000:${FRONTEND_PORT}

  mysql:
    image: mysql:8.0
    volumes:
      - persistant-mysql:/var/lib/mysql
      - ./db-startscripts/:/docker-entrypoint-initdb.d
    
    expose:
      - 3306

    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}


volumes:
  persistant-mysql: